-- Repair tutor listings that onboarding left unusable.
--
-- Onboarding only ever wrote catalog services, while the marketplace reads
-- Tutor."hourlyCents" and Subject rows. Neither was written, so tutors who
-- finished onboarding and published are listed at $0/hr with no subjects — and
-- since a booking is priced from "hourlyCents", they can be booked for free.
--
-- The application now derives both from the catalog on every service change.
-- This brings existing rows up to that state once.

-- 1. A subject per distinct service name/level the tutor offers.
--    Matched case-insensitively, as the application does, so "Math" and "math"
--    do not become two subjects. Subject ids are uuids generated by the client,
--    so the column has no default and one must be supplied here.
INSERT INTO "Subject" (id, name, level, "tutorId")
SELECT gen_random_uuid(), s.name, s.level, s."tutorId"
FROM (SELECT DISTINCT "tutorId", name, level FROM "Service") s
WHERE NOT EXISTS (
  SELECT 1 FROM "Subject" sub
  WHERE sub."tutorId" = s."tutorId"
    AND sub.level = s.level
    AND lower(sub.name) = lower(s.name)
);

-- 2. Point services at the subject they describe, so bookings made against a
--    subject can be traced back to what was sold.
UPDATE "Service" srv
SET "subjectId" = sub.id
FROM "Subject" sub
WHERE srv."subjectId" IS NULL
  AND sub."tutorId" = srv."tutorId"
  AND sub.level = srv.level
  AND lower(sub.name) = lower(srv.name);

-- 3. Rate from the cheapest live service, normalised over the total teaching
--    time it buys, so a package and a single lesson agree. Same arithmetic as
--    CatalogService.syncHourlyRate.
--
--    Only tutors with no usable rate are touched. Seeded tutors already have a
--    rate that may not match their catalog; repricing them is not this
--    migration's business, and their next catalog edit resyncs them anyway.
UPDATE "Tutor" t
SET "hourlyCents" = r.rate
FROM (
  SELECT "tutorId",
         MIN(ROUND(("priceCents"::numeric / ("durationMin" * "lessonsCount")) * 60))::int AS rate
  FROM "Service"
  WHERE "isActive" = true
    AND "priceCents" > 0
    AND "durationMin" * "lessonsCount" > 0
  GROUP BY "tutorId"
) r
WHERE t.id = r."tutorId"
  AND t."hourlyCents" <= 0;

-- 4. Anything still priced at zero has no live service to price it, so it
--    cannot be booked for anything but free. Take it out of the marketplace;
--    the tutor can republish once they add one, which publishProfile now
--    requires.
--
--    Deliberately not unpublishing for missing availability: that only makes a
--    tutor unbookable, which is inconvenient rather than exploitable.
UPDATE "Tutor"
SET "isActive" = false
WHERE "isActive" = true
  AND "hourlyCents" <= 0;
